version: "2"

services:

  mariadb:
    image: wodby/drupal-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
#      - ./databases/init:/docker-entrypoint-initdb.d  # Place init .sql file(s) here.
      - ./runtime/mariadb:/var/lib/mysql
      - ./databases:/var/lib/mysql/databases


  php:
#    image: wodby/drupal-php:7.0
    image: wodby/drupal-php:5.6
    restart: unless-stopped
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      #PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      #PHP_XDEBUG_AUTOSTART: 1
      #PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      #PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
      PHP_MAX_INPUT_VARS: 5G
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      # - codebase:/var/www/html
      - ./:/var/www/html
      - ./runtime/drush:/home/www-data/.drush


  apache:
    image: wodby/php-apache:2.4-2.0.2
    depends_on:
      - php
    restart: unless-stopped
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/www
      APACHE_SERVER_NAME: localhost
    volumes:
      - ./:/var/www/html
    networks:
      - default
      - traefik_proxy
    labels:
      - 'traefik.backend=drupal_apache'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:eliotme.dt7.vt-s.net'
      - "traefik.docker.network=traefik_proxy"


  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      # Deprecated
      VIRTUAL_HOST: eliotme.pma.loc
    volumes:
      - ./runtime/metro:/www/themes/metro
      # Add custom pma configuration e.g. to prevent timeout https://docs.phpmyadmin.net/en/latest/config.html#config
#      -v ./runtime/pma-config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - default
      - traefik_proxy
    labels:
      - 'traefik.backend=drupal_pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:eliotme.pma.loc'


  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    environment:
      # Deprecated
      VIRTUAL_HOST: eliotme.hog.loc
      VIRTUAL_PORT: 8025
    networks:
      - default
      - traefik_proxy
    labels:
      - 'traefik.backend=drupal_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:eliotme.hog.loc'
      - "traefik.docker.network=traefik_proxy"
#  elasticsearch:
#    image: elasticsearch:alpine
#    restart: unless-stopped
#    # Clustering support
#    environment:
#      - transport.host:0.0.0.0
#      - discovery.zen.minimum_master_nodes:1
#    volumes:
#      - ./runtime/elasticsearch/data:/usr/share/elasticsearch/data
#      - ./runtime/elasticsearch/config:/usr/share/elasticsearch/config
#    networks:
#      - proxy_net
#      - default
#

  redis:
    image: redis:3.0.7
    restart: unless-stopped
    labels:
     - 'traefik.frontend.rule=Host:redis.eliotme.loc'

#  memcached:
#    image: memcached:1.4-alpine
#  memcached-admin:
#    image: phynias/phpmemcachedadmin
#    ports:
#      - "8047:80"

  solr:
   image: wodby/drupal-solr:7-5.4-2.3.0
   restart: unless-stopped
   environment:
     SOLR_HEAP: 1024m
   labels:
     - 'traefik.backend=solr'
     - 'traefik.port=8983'
     - 'traefik.frontend.rule=Host:solr.eliotme.loc'
     - "traefik.docker.network=traefik_proxy"
   networks:
     - traefik_proxy
     - default


  varnish:
    image: wodby/drupal-varnish
    depends_on:
      - apache
    restart: unless-stopped
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: apache
      VARNISH_BACKEND_PORT: 80
      VARNISH_MEMORY_SIZE: 256M
      VARNISH_STORAGE_SIZE: 1024M
    labels:
      - 'traefik.backend=varnish'
      - 'traefik.port=6081'
      - 'traefik.frontend.rule=Host:varnish.eliotme.loc'


  clamav:
     image: mkodockx/docker-clamav
     restart: unless-stopped
     ports:
       - "3310:3310"
     networks:
       - default

networks:
  traefik_proxy:
    external: true